name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Update README
        run: |
          cd scripts
          node update.js

      - name: Commit and push if changed
        run: |
          git diff
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Update README" || echo "No changes to commit"
          git push
